### ISSUE TITLE
Voice Fill is not entirely removed from the supported pages, if the experiment it's disabled/removed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/speaktome#109]
[Notes]:
- This scenario will be easily encountered on Test Pilot when the users have the ability to enable and disable the experiment at will.

[Affected versions]:
- Firefox 54.0.1 and above

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version installed.

[Steps to reproduce]:
1. Open the Firefox with the profile from prerequisite and navigate to "https://www.google.com" page.
2. In a new tab navigate to "about:addons" page and choose to disable/remove the add-on.
3. Return and observe the Google page.

[Expected result]:
- The add-on is successfully disabled/removed and is no longer displayed on the sported pages.

[Actual results]:
- The add-on is successful disabled/removed, but some remains of Voice Fill can be observed on the page.

[Additional Notes]:
- This issue is also reproducible on Yahoo and DuckDuckGo pages.
- The issue disappears if the page is refreshed.
- Here is a screen recording with the issue:
![remains of voice fill](https://user-images.githubusercontent.com/19226534/28621918-3a3c045a-721b-11e7-946d-ffc03dd17274.gif)

**Comment by johngruen** [comment]
Not sure how we would handle stripping out content on add-on uninstall

**Comment by johngruen** [comment]
This is upstream. Filed this: https://bugzilla.mozilla.org/show_bug.cgi?id=1394916
