### ISSUE TITLE
Awkward rename of "testpilot-ga" to "testpilot-qa"

### ISSUE THREAD

**Issue by pdehaan** [mozilla/speaktome#112]
I saw a floating reference to "testpilot-qa" module somewhere and was excited since I thought we outsourced my job to an npm module, but turns out that it looks like a odd rename of "ga" => "qa" during `npm postinstall` hook:

```js
"postinstall": "cp node_modules/testpilot-ga/dist/index.js extension/testpilot-qa.js"
```

https://github.com/mozilla/speaktome/search?utf8=%E2%9C%93&q=testpilot-qa&type= shows at least 3 instances that would need to change:

1. [/.eslintignore:2](https://github.com/mozilla/speaktome/blob/2e2cc14b88c9553475d895612aa139e50fa8cde5/.eslintignore#L2) &mdash; `extension/testpilot-qa.js`
1. [/package.json:38](https://github.com/mozilla/speaktome/blob/856aa1f2cca844e6539dc98aaa33b99d3d1cb6d2/package.json#L38) &mdash; `"postinstall": "cp node_modules/testpilot-ga/dist/index.js extension/testpilot-qa.js"`
1. [/extension/manifest.json:46](https://github.com/mozilla/speaktome/blob/f3332ca453ddef9e30ccd5c86e09dc08f930bcb3/extension/manifest.json#L46) &mdash; `"scripts": ["testpilot-qa.js", "background.js"]`

**Comment by andrenatal** [comment]
I copied that from notes. We should fix there too https://github.com/mozilla/notes/blob/5afd3c05f1f45059a3679b9f558259d5245cd879/scripts/postinstall.sh#L5

**Comment by pdehaan** [comment]
Submitted PR to Notes: https://github.com/mozilla/notes/pull/173

**Comment by andrenatal** [comment]
This was fixed by https://github.com/mozilla/speaktome/pull/126
