### ISSUE TITLE
Loading Voice Fill as a temporary add-on wrongly breaks its UI and some of the functionalities

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#120]
Affected versions]:
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.8 downloaded from the repository) installed as a temporary add-on (through about:debugging).

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Observe the UI of the page.

[Expected result]:
- Voice fill elements are properly displayed on the page and all its functionalities work as expected.

[Actual result]:
- Same behavior experienced in the following issues happen again: [79](https://github.com/mozilla/speaktome/issues/79), [80](https://github.com/mozilla/speaktome/issues/80), [81](https://github.com/mozilla/speaktome/issues/81), [82](https://github.com/mozilla/speaktome/issues/82), [83](https://github.com/mozilla/speaktome/issues/83)

[Notes]:
- This is not reproducible on Beta and Release.
- The issue is reproducible on all supported websites.
- Added a screen cast with the issue:

![temporary addon](https://user-images.githubusercontent.com/26000308/28662065-800df406-72c1-11e7-9f8b-ebccce58b88a.gif)

**Comment by wresuolc** [comment]
Assuming this works fine after you reload the page, we're not considering this within scope to fix.  Thanks.
