### ISSUE TITLE
Make Sure Metrics are Being Recorded in Release Candidate

### ISSUE THREAD

**Issue by johngruen** [mozilla/speaktome#124]
Just a reminder to confirm that files all wind up in the right place in our next RC

**Comment by andrenatal** [comment]
Just double checked and yes they are being recorded properly.

**Comment by wresuolc** [comment]
https://screenshots.firefox.com/VJV4TkJf8ZBi0mL2/analytics.google.com

    looks like we are logging an object instead of a string
