### ISSUE TITLE
Clicking the overlay while recording dismisses it and automatically starts the search process

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#128]
[Affected versions]:
- Release 54.0.1 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version 1.2.8 installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone button.
3. Click once or twice on the overlay.

[Expected result]:
- Nothing happens, the recording session takes place without interruptions.

[Actual result]:
- The overlay is dismissed and the search starts automatically with one of the default suggested answers.

[Notes]:
- This is reproducible on all supported websites.
- Added a screen cast with the issue:

![click on overlay](https://user-images.githubusercontent.com/26000308/28677590-9b5a6bf6-72f6-11e7-9e21-edfc93394eb0.gif)

**Comment by wresuolc** [comment]
This is a google issue where they prefetch results before you submit.  Similar to another issue filed here earlier.
