### ISSUE TITLE
Suggested input and drop down shrink their length if "Backspace" key is pressed multiple times

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#136]
Affected versions]:
- Release 54.0.1 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version 1.2.8 installed.
- Tools -> Page Info -> Permissions -> "Use Default" is unchecked and "Allow" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone button.
3. Say a long sentence.
4. Move the text pointer to the left side of the input, before the first letter.
5. Press "Backspace" key multiple times and observe what happens next.

[Expected result]:
- Nothing happens, the input's and drop down's list size doesn't suffer any changes.

[Actual result]:
- Both the input and drop down length shrink.

[Notes]:
- This is also reproducible by using the "Delete" key (in this case, the text inside the input is deleted).
- This is reproducible on all supported websites.
- Added a screen cast with the issue:

![jfjfd](https://user-images.githubusercontent.com/26000308/28780827-cff10650-7610-11e7-97d1-48b351ee0404.gif)

**Comment by wresuolc** [comment]
@johngruen says he just made this better, but overall it's a feature and not a bug.
