### ISSUE TITLE
Add start.duckduckgo.com to domain list

### ISSUE THREAD

**Issue by johngruen** [mozilla/speaktome#148]

**Comment by wresuolc** [comment]
PR exists

**Comment by johngruen** [comment]
This PR exists but need to be included in the switch statement in content.js

**Comment by andrenatal** [comment]
Fixed by #181

**Comment by Softvision-CristinaBadescu** [comment]
The microphone button is successfully displayed on the "start.duckduckgo.com" domain on the pre-release Voice Fill v.1.3.1 on 9/18/2017.
