### ISSUE TITLE
Add Voice Fill to about:newtab and about:home

### ISSUE THREAD

**Issue by Aljullu** [mozilla/speaktome#150]
It feels weird to have Voice Fill in Google, Yahoo and DuckDuckGo but not in the search fields inside Firefox. I'm referring to `about:newtab` and `about:home`.
![screenshot from 2017-08-05 00-05-30](https://user-images.githubusercontent.com/3616980/28988807-fc439006-7971-11e7-80be-9eb5a2001389.png)

**Comment by mrstegeman** [comment]
Duplicates #7
