### ISSUE TITLE
Voice Fill triggers the in page search suggest menu

### ISSUE THREAD

**Issue by shorlander** [mozilla/speaktome#160]
STR:
- Go to google.com or yahoo.com
- Do a search
- Resulting SERP page triggers the search suggest menu

Expected Results:
- Does not trigger the search suggest menu

**Comment by johngruen** [comment]
difficulty here is that we need to focus the inputs but they automatically trigger the dropdown in focus. We'd have to figure out a workaround for this.

**Comment by SoftVision-PaulOiegas** [comment]
@shorlander are you referring that it should automatically search for the spoken string? If not, I personally don't consider this an issue. Any search field does the same... The only difference I see on Chrome, is that voice search actually performs the search.

**Comment by SoftVision-PaulOiegas** [comment]
@shorlander Wait, are you doing a voice search or written search? If you refer to written search, then yeah, this is a valid bug that only occurs when Voice Fill is installed and enabled (see recording https://goo.gl/dqLri1).

If this is not the case, please let us know sicne we would need to log a separate issue for it.

**Comment by shorlander** [comment]
Yes, this is with a typed search with Voice Fill installed.

**Comment by SoftVision-CarmenFat** [comment]
Tested this with the pre-release Voice Fill v.1.3.1 and the search engine results page doesn't display anymore the drop down with the suggestions.
