### ISSUE TITLE
Idea: Voice Fill button in toolbar

### ISSUE THREAD

**Issue by sevaan** [mozilla/speaktome#162]
Feature idea:

Add the Voice Fill icon to the toolbar so a user can click on it and perform a search on the user's default search engine without them having to manually go to a search engine first.

**Comment by sevaan** [comment]
Dupe of Issue #146.
Awesome bar is a better place for it than the toolbar probably.

**Comment by johngruen** [comment]
@sevaan not a dupe...

**Comment by andrenatal** [comment]
@sevaan This is being worked out and version[ 1.3.6 ](https://github.com/mozilla/speaktome/releases/tag/1.3.6) already fulfill this request
