### ISSUE TITLE
Typo in name of contributor on experiment page

### ISSUE THREAD

**Issue by fmarier** [mozilla/speaktome#164]
`Fabrice` is incorrectly spelled `Frabrice` on https://testpilot.firefox.com/experiments/voice-fill.
![testpilot-voicefill-typo](https://user-images.githubusercontent.com/167821/29145566-86cf37f4-7d12-11e7-8db5-f452b71bb7d7.png)

**Comment by pdehaan** [comment]
Good catch, @fmarier!
That's super embarassing, sorry. PR submitted at https://github.com/mozilla/testpilot/pull/2756.

**Comment by SoftVision-PaulOiegas** [comment]
Looks good now. 👍
