### ISSUE TITLE
Voice Fill not enabled for Google Search Engine-https://www.google.co.in

### ISSUE THREAD

**Issue by Radhraj** [mozilla/speaktome#165]
Search Engines like DuckDuckGo the Voice Fill option is enabled .
But the same plugin is not available for Google India.

![voicefillnotenabledforgoogleindia](https://user-images.githubusercontent.com/30893077/29203786-cc3fda3a-7e90-11e7-9906-87aa5f597d06.gif)

**Comment by marwendoukh** [comment]
Hi @Radhraj , I did a pull request on that ( #145 ) , hoping it will be merge soon .

**Comment by johngruen** [comment]
This is a dupe @marwendoukh's PR is going to get merged soon
