### ISSUE TITLE
User must be notified with correct error message in case of MicroPhone being switched off/Disabled

### ISSUE THREAD

**Issue by Radhraj** [mozilla/speaktome#168]
Steps to reproduce:

    Open the browser which has Voice Fill plugin enabled
    Click on Voice Fill option.
    Disable Microphone when prompted.

Expected Result:
The error message must exactly tell why the issue occurred.

Actual Result:
It throws "Sorry We encountered an error" error on switching off the microphone.

Notes:
If the Microphone is not allowed the access, then on clicking on Voice Fill it says "Sorry We encountered an error"
The error must exactly specify what it is for the user to understand why the error occurred or what made the plugin or feature to fail.

Attached Screenshot:

![usernotifyonmicrodisabled](https://user-images.githubusercontent.com/30893077/29204595-982e198c-7e95-11e7-9181-c56f916e87ae.gif)

**Comment by johngruen** [comment]
the specific string should be "Please enable your microphone to use Voice Fill", this should display with the error mic if the user rejects the mic popup

**Comment by Softvision-CristinaBadescu** [comment]
The general message has been replaced with a more specific one: "Please enable your microphone to use Voice Fill". The issue is no longer reproducible on the pre-release Voice Fill v.1.3.1 on 9/18/2017.
