### ISSUE TITLE
Voice Fill doesn't display the multiple answers overlay if the previous search was dismissed through ESC key

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#191]
[Affected versions]:
- Firefox 55.0.3 and up
- Voice Fill 1.3.0

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Latest Voice Fill add-on 1.3.0 (custom repo built on 9/14/2017) was previously installed on a clean profile.
- Tools -> Page Info -> Permissions -> Use the Microphone -> "Use Default" is unchecked and "Allow" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a supported website.
2. Click on the microphone button and say something.
3. Press ESC key when the multiple answers overlay is displayed. 
4. Click again on the microphone button and say something.
5. Observe what happens next.

[Expected result]:
 - After processing the recorded data, the multiple answers overlay is displayed.

[Actual result]:
- "Processing..." overlay is stuck.

[Notes]:
- This issue doesn't happen when dismissing the Voice Fill overlay through "X" button.
- Attaching a screen recording of the issue:

![esc key overlay](https://user-images.githubusercontent.com/26000308/30429640-de8fcda4-9960-11e7-9d50-977118435b69.gif)

**Comment by andrenatal** [comment]
@SoftVision-CarmenFat please let me know if this is still reproducible for you.

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Voice Fill custom repo built on 9/19/2017 (v.1.3.1).
