### ISSUE TITLE
The Microphone permission doorhanger is no longer displayed in latest Nightly (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/speaktome#206]
[Notes]:
- This is a Firefox issue and it's already logged on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1388545#c6
- This issue is not reproducible on Ubuntu 16.04 x64 and Ubuntu 16.04 x32.

[Affected versions]:
- Nightly 57.0a1
- Voice Fill 1.3.1

[Affected Platforms]:
- Ubuntu 14.04 x64
- Ubuntu 14.04 x32

[Prerequisites]:
- Latest Voice Fill add-on 1.3.1 (custom repo built on 9/20/2017) was previously installed on a clean profile.
- Tools -> Page Info -> Permissions -> Use the Microphone -> "Use Default" is unchecked and "Always Ask" is checked.

[Steps to reproduce]
1. Open the browser with the profile from prerequisites and navigate to a supported website.
2. Press the Microphone button placed in the right side of the search bar.
3. Observe the behavior. 

[Expected results]
- The Microphone permission doorhanger is displayed.

[Actual results]
- The "Please enable your microphone to use Voice Fill" message appears and the Microphone permission doorhanger is not displayed.

[Additional Notes]:
- Here is a screen recording of the issue: https://goo.gl/az1jHy

**Comment by johngruen** [comment]
Wontfix due to upstream issue
