### ISSUE TITLE
A blank space is displayed instead of the "Voice Fill" toolbar button

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#223]
[Notes]:
- After clicking the blank space, the following error message is displayed in the browser console:
```
TypeError: asm.js type error: Disabled by 'asmjs' runtime option  webrtc_vad.js
unreachable code after return statement  bodymovin.js:2200:8
```

[Affected versions]:
- Firefox 56.0.2 and up
- Voice Fill v.1.3.2

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the Voice Fill (v. 1.3.2) experiment installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Observe the "Voice Fill" toolbar button.

[Expected result]:
- The "Voice Fill" toolbar button is correctly displayed.

[Actual result]:
- A blank space is displayed instead of the "Voice Fill" toolbar button.

[Additional Notes]:
- Attached a screen recording of the issue:

![voice fill icon](https://user-images.githubusercontent.com/26000308/32271175-5c0d1b18-bf01-11e7-8514-8b06b3b19823.gif)

**Comment by andrenatal** [comment]
Fixed by https://github.com/mozilla/speaktome/commit/fa4c80fc0b4a367bfbc8db10315ee5ffafffbf83
