### ISSUE TITLE
The microphone button next to the search field is actionable while recording if triggering the voice search from toolbar

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#231]
[Affected versions]:
- Firefox 56.0.2 and up
- Voice Fill v.1.3.4

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the Voice Fill (v. 1.3.4) experiment installed.
- Tools -> Permissions -> "Use default" is unchecked and "Allow" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Voice Fill button from the toolbar.
3. Observe and click the Microphone button from the right side of the search engine.

[Expected result]:
- The microphone button from the right side of the search engine is greyed out and cannot be clicked.

[Actual result]:
- The microphone button from the right side of the search engine field is actionable and can be clicked once, interrupting the recording session.

[Notes]:
- See also: [#95](https://github.com/mozilla/speaktome/issues/95) 
- Attached a screen recording of the issue:

![button action](https://user-images.githubusercontent.com/26000308/32337112-cb1ded04-bff9-11e7-8d35-7fac5e00687f.gif)

**Comment by Softvision-CristinaBadescu** [comment]
I can confirm that this issue is no longer reproducible using latest Voice Fill v. 1.3.4.1, on latest Nightly build 58.0a1 (2017-11-05), on Windows 10 x64, Mac 10.12 and Ubuntu 14.04 x64.
