### ISSUE TITLE
Old Firefox logo is displayed on the Voice Fill overlay

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#239]
[Affected versions]:
- Firefox 57 and up
- Voice Fill v.1.3.4 (custom built from repo on 11/15/2017)

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the Voice Fill (v. 1.3.4) experiment installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Click the Voice Fill button from the toolbar (or from one of the supported search pages). 
3. Observe the Firefox logo from the bottom left of the overlay.

[Expected result]:
- The new Firefox logo is displayed.

[Actual result]:
- The old Firefox logo is displayed.

[Notes]:
- Attached a screenshot of the issue:

![old logo](https://user-images.githubusercontent.com/26000308/32838825-eb822102-ca1a-11e7-970d-85f58c9da6dd.png)

**Comment by johngruen** [comment]
I fixed this in my PR

**Comment by SoftVision-CarmenFat** [comment]
This is no longer reproducible with the pre-release version (v.1.3.5).
