### ISSUE TITLE
Graduate from Test Pilot!

### ISSUE THREAD

**Issue by wresuolc** [mozilla/speaktome#249]
Congratulations on a successful Test Pilot run!  We'd like to get this in AMO.  Below are the steps to do that:

-  [x] Drop the UpdateURL.  Just delete the whole line.  Without it specified, it defaults back to AMO.
-  [x] Drop any Telemetry.  We need to not send anything to Telemetry.
-  [x] Upload the new add-on to AMO.  When uploading the new add-on be sure to change the "How to distribute" option to be AMO instead of "on your own"
-  [x] Disable the install button on Test Pilot (publish the graduation report)
- [ ] Stop building the add-on in Test Pilot
-  [ ] Wil can redirect existing users to the AMO version.  They'll get the new version as their browser checks for updates (once a day)

**Comment by andrenatal** [comment]
@johngruen @wresuolc first two issues were addressed.

**Comment by wresuolc** [comment]
For the last bullet point about redirecting users...I don't think that's a thing anymore.  We put the latest version on Test Pilot without the updateURL specified, which means users will update to that, and then future checks will go to AMO.  So, I guess that checkbox is leftover from an old system.

Anyway, we're done here.  Thanks!

**Comment by wresuolc** [comment]
@andrenatal The best option, I think, is the stats dashboard on AMO: https://addons.mozilla.org/en-US/firefox/addon/voice-fill/statistics/?last=30

You could also install an old version, then choose 'check for updates' and make sure you get the one on AMO.  You might have to check for updates twice, depending on how old the version is.
