### ISSUE TITLE
Hook Voice Fill up to Test Pilot

### ISSUE THREAD

**Issue by wresuolc** [mozilla/speaktome#25]
1) We need to make this repository match the spec at https://github.com/mozilla/testpilot/blob/master/docs/development/hosting.md

2) @relud to add this repository to the watcher

**Comment by pdehaan** [comment]
Wait, is "Voice Fill" the final product name?
If so, can we rename the repo and I can PR the README.md file

**Comment by wresuolc** [comment]
I copied https://github.com/bwinton/SnoozeTabs/blob/master/bin/build-addon.sh for hoverpad

**Comment by wresuolc** [comment]
Script has landed and I verified it works (got a signed add-on on AMO out of it).

miles is working on the ops side now

**Comment by wresuolc** [comment]
Ok, stuff on the production branch is now showing up at https://testpilot.firefox.com/files/@speak-to-me/latest .  If you install that add-on you'll automatically get updates when new versions are pushed.

**Comment by pdehaan** [comment]
FWIW, if I download that XPI and inspect the contents, it seems to be pointing to a stage server.
```js
const stt_server_url = "https://speaktome.stage.mozaws.net";
```
