### ISSUE TITLE
Load testing for v1

### ISSUE THREAD

**Issue by wresuolc** [mozilla/speaktome#26]
We're talking about having Stage available on July 11th for load testing.  This is a really tight squeeze for launching on July 18th.  This issue is to track load testing.

/cc @oremj @milescrabill @jvehent

**Comment by jvehent** [comment]
Do we need anything more than a curl loop that sends a few dozen opus blobs and/or random data per second?

**Comment by wresuolc** [comment]
That's fine.  We can just collect a few POST submissions and then replay them.  We should do real blobs instead of random so it actually has to process them.

**Comment by pdehaan** [comment]
I really like the [**mozilla-services/screenshots**](https://github.com/mozilla-services/screenshots/blob/1b7b5ad0d84994145311dcd5e4fb2ac5799a223c/bin/load_test_exercise.py#L108-L109) approach of having a JSON file with some valid sample data, and we just choose some random payload from a predefined set.

**Comment by pdehaan** [comment]
Ref: #53

**Comment by andrenatal** [comment]
@pdehaan You can use this script to save opus files: https://github.com/mozilla/speaktome/issues/53#issuecomment-315966406

**Comment by wresuolc** [comment]
@milescrabill says our throughput is pretty low, and we'll need to scale horizontally until we solve that.  Sounds like the ASR server is the choke point.

For launch, we'll be prepared to scale on servers while we collect data on how often users use this service.  Stats will be in datadog, although putting them in GA would be 🍠

**Comment by chuckharmston** [comment]
> putting them in GA would be 🍠

Ref #104

**Comment by wresuolc** [comment]
@pdehaan is this closable? :)

**Comment by pdehaan** [comment]
@wresuolc Everything is closeable... if you believe in yourself! 🦄 

But yeah, we've done load tests. We'll continue to do more as stacks change and we do more testing. No point/value in keeping this open though, IMO.
