### ISSUE TITLE
Icon won't show on google.

### ISSUE THREAD

**Issue by GoodDays13** [mozilla/speaktome#269]
When I open google, no voice fill icon shows, but it works on DuckDuckGo.
![desktop screenshot 2018 08 31 - 15 57 29 13](https://user-images.githubusercontent.com/42877449/44933311-9ede2d00-ad36-11e8-8527-a0e6964bccbc.png)
![desktop screenshot 2018 08 31 - 15 57 36 95](https://user-images.githubusercontent.com/42877449/44933314-a1408700-ad36-11e8-8421-79308fc05d7d.png)

**Comment by GoodDays13** [comment]
It worked before.

**Comment by andrenatal** [comment]
Thanks for reporting this @GoodDays13! We just fixed it on https://github.com/mozilla/speaktome/pull/270

Could you please give it another try and reopen this if is still broken?

**Comment by andrenatal** [comment]
Am closing this since it was reported to be working.

**Comment by GoodDays13** [comment]
Sorry for not replying but it works now.
