### ISSUE TITLE
When using google normally, hitting 'enter' opens the voice fill add-on

### ISSUE THREAD

**Issue by DavidHanover** [mozilla/speaktome#273]
instead of submitting your search bar.

this is extremely, EXTREMELY annoying.  i only want to use voice fill when i choose.  i could understand this feature being standard due to folks who can't type well, or rather, accessibility reasons.  But there should be an option in the menu to disable this behavior.  i only want voice fill to open when i click the icon, not when i hit the 'enter' key on google.

**Comment by andrenatal** [comment]
Hi @DavidHanover, thanks for reporting this behavior. We pushed new a version containing a fix for this issue. Is this still happening for you on version 1.4.2?

**Comment by DavidHanover** [comment]
no prob!  behavior is fixed, thanks for the update.

**Comment by andrenatal** [comment]
Thank you @DavidHanover
