### ISSUE TITLE
Unable to search on apple.com

### ISSUE THREAD

**Issue by pdehaan** [mozilla/speaktome#31]
```sh
$ git rev-parse --short HEAD # 28cc402
```

### Steps to reproduce:

1. `npm run build`
1. `npm run once`
1. Go to https://apple.com
1. Click the search icon in the top toolbar.
1. Try and click the Speak-To-Me icon.

### Actual results:
I don't seem to be able to click the speak-to-me icon in the text input field in order to grant microphone access and do a voice search.

<img width="1022" alt="apple" src="https://user-images.githubusercontent.com/557895/27716153-2d02a814-5cf1-11e7-82c2-06fd3782b8d5.png">

### Expected results:
Able to search by voice.

**Comment by clouserw** [comment]
This is not a launch feature.  For launch, we are only targeting about:home, about:newtab, and context menus.

**Comment by johngruen** [comment]
out of scope for launch
