### ISSUE TITLE
Save voice sample and submitted text with a method respecting a user's privacy

### ISSUE THREAD

**Issue by wresuolc** [mozilla/speaktome#32]
When saving the voice sample:

-    Ensure the voice data is not associated with any person-identifiers, including Firefox or Test Pilot identifiers
-    Don't send the voice sample to two places
-    No requirement to delete within a time frame

/cc @eleemoz @johngruen

@andrenatal : Can you sketch a diagram of how this works? Kaldi can probably save a sample, but we need to do a separate ping for what was submitted? let's talk!  Doesn't need to be a diagram necessarily, just need a plan for this.

**Comment by wresuolc** [comment]
This also needs to get added to the metrics docs

**Comment by wresuolc** [comment]
This has a bullet point in our privacy doc now

**Comment by eleemoz** [comment]
Still needs to be added to https://github.com/mozilla/speaktome/blob/master/docs/metrics.md once implementation is more complete though.

**Comment by jbuck** [comment]
This is currently being done via uploading the opus audio and the json response from kaldi to S3. The only data associated with these two files is a random UUID generated by the server & the upload time.

Each environment has its own S3 bucket for uploading files. There's no lifecycle policy on the bucket to delete files after a certain amount of time.

There's no storage of what the user has selected.
