### ISSUE TITLE
The microphone button is not displayed inside the search input on the main page of Bugzilla

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#33]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 05/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://bugzilla.mozilla.org/
3. Click inside either of the 2 search inputs and observe what happens next.

[Expected result]:
- The microphone button is displayed inside the search input.

[Actual results]:
- The microphone button is not displayed inside the search input.

[Notes]:
- On the other pages of Bugzilla the microphone button is properly displayed.
- Here is a screen cast of the issue:

![bugzilla](https://user-images.githubusercontent.com/26000308/27870615-fbc0b3bc-61ab-11e7-8055-b15396934479.gif)

**Comment by clouserw** [comment]
This is not a launch feature.  For launch, we are only targeting about:home, about:newtab, and context menus.

**Comment by johngruen** [comment]
Not supported
