### ISSUE TITLE
The microphone button doesn't remain inside the search input while scrolling on some websites

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#38]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 05/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to https://us.yahoo.com/
3. Scroll down and up with different speed using middle click.
4. Observe the microphone button.

[Expected result]:
- The microphone button remains in the same position inside the search input. 

[Actual results]:
- The microphone button doesn't keep up with the speed of scrolling and it's placed outside the search input.

[Notes]:
- This issue is also reproducible on other websites (https://twitter.com/, https://www.aliexpress.com/)
- Here is a screencast of the issue:

![yahoo](https://user-images.githubusercontent.com/26000308/27899080-71952c3c-6231-11e7-8525-08bedbb3b464.gif)

**Comment by wresuolc** [comment]
@johngruen -- is yahoo on the launch list?

**Comment by clouserw** [comment]
Answer: no

**Comment by SoftVision-CarmenFat** [comment]
Closing this since it's the old Voice Fill UI and I can't reproduce it anymore with the latest Voice Fill v.1.3.0.

Tested with:
https://us.yahoo.com/
https://uk.yahoo.com/
https://ca.yahoo.com/
