### ISSUE TITLE
Microphone button is moved outside the search input if clicked on Imgur

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#39]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 05/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.imgur.com
3. Click on the magnifying glass search button.
4. Click on the microphone button and observe what happens next.

[Expected result]:
- Permission door hanger to access the microphone is triggered. 

[Actual results]:
- The door hanger is not triggered and the microphone button is moved outside the search input, to the right side of the website's area.

[Notes]:
- Here is a screencast of the issue:

![imgur](https://user-images.githubusercontent.com/26000308/27899334-76da3fec-6232-11e7-814e-32aec51ffd2d.gif)

**Comment by wresuolc** [comment]
imgur isn't supported at launch so I'm closing this.  The other microphone placement issues should address this (and a new design coming next week)
