### ISSUE TITLE
There is no description of the Voice Fill/Speak To Me add-on in "about:addons" page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#40]
[Affected versions]:
- Release 54.0.1 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 05/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons" page.
3. Click on "Extensions" option from the left sidebar.
4. Observe the way the "speak-to-me" add-on is described.

[Expected result]:
- A text containing a brief description of the add-on is displayed under the add-on title.

[Actual results]:
- There is no text description of the add-on.

**Comment by wresuolc** [comment]
@johngruen we need text for this

**Comment by johngruen** [comment]
on it

**Comment by SoftVision-CarmenFat** [comment]
The issue is no longer reproducible on the latest Voice Fill version (1.2.3)
The Voice Fill title, microphone icon and a brief description of the add-on are displayed on the about:addons page.
