### ISSUE TITLE
Microphone button is wrongly overlapped by websites toolbars

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#41]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 05/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.youtube.com
3. Observe the search input.
4. Using middle click scroll down and up the website very fast.
5. Observe the website's content area under the toolbar's search input.

[Expected result]:
3. The microphone button is displayed inside the search input.
5. The microphone button remains inside the search box and the content area is correctly displayed.

[Actual results]:
3. The microphone button is not displayed inside the search input.
5. The microphone button can be observed under the toolbar's search input, over the website's content area. 

[Notes]:
- This issue is also reproducible on www.msn.com
- Here is a screen recording with the issue (since the issue is hard to notice because of the website's content, I zoomed out the website for a better view of this bug):

![youtube](https://user-images.githubusercontent.com/26000308/27899907-cecb770a-6234-11e7-9c8a-357c4895a10f.gif)

**Comment by johngruen** [comment]
I don't think we support MSN

**Comment by SoftVision-PaulOiegas** [comment]
@johngruen The issue was observed on YouTube, MSN was just as an "see also". 
However, I am unable to reproduce this issue.  Tried on new YouTube UI and old UI and tried with Nightly, Beta and Release channels. Not a single mike icon observed. Even tried with today custom build made from repo and TxP build with no success.

@SoftVision-CarmenFat Is this still reproducing on your end?

**Comment by SoftVision-CarmenFat** [comment]
- Neither YouTube nor MSN are supported websites for the current version of Voice Fill.
- This issue was logged back when the current UI wasn't ready and the supported websites were not determined.
- I don't have anything to test regarding this issue, unless the 2 mentioned webpages become part of the supported websites.
