### ISSUE TITLE
The microphone button overlaps other search input special buttons on some websites

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#42]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 05/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites.
2. Navigate to www.wikipedia.org
3. Observe the search input items.

[Expected result]:
- The microphone button is placed in a way that doesn't overlap other UI elements nor blocks other search input buttons. 

[Actual result]:
- The microphone button overlaps a part of the locales switcher button.

[Notes]:
- This is also reproducible on other websites: 
1. http://www.jd.com/ - the special search button is not clickable
2. https://yandex.ru/ - the keyboard button is overlapped by the microphone button
- Here is a screencast of the issue:

![wikipedia](https://user-images.githubusercontent.com/26000308/27900456-1fcaaed0-6237-11e7-8c48-02a185d7eb8d.gif)

**Comment by johngruen** [comment]
Old UI
