### ISSUE TITLE
Microphone button is wrongly displayed outside the email input on the Pinterest "Log in" page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#43]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 06/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://www.pinterest.com/
2. Click on the "Log in" button on top right of the screen.
3. Observe the microphone's button location on the page.

[Expected result]:
- The microphone button is displayed inside the email or phone input.

[Actual results]:
- The microphone button is displayed outside the email or phone input, overlapping the "Log in" button.

[Notes]:
- On "Welcome" page, the microphone button is correctly displayed inside the email input.
- Here is a screencast of the issue:

![login pinterest](https://user-images.githubusercontent.com/26000308/27913830-0486061e-626a-11e7-9197-82ba34ac5f8c.gif)

**Comment by wresuolc** [comment]
At launch we're only supporting a couple of sites (not pinterest) so I'm going to close this.  @johngruen -- do you have a list of supported sites at launch?
