### ISSUE TITLE
Website's toolbar doesn't cover the microphone button if the page is scrolled down

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#44]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 06/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://faq.whatsapp.com/
2. Click inside the search input.
3. Scroll down until the search input is covered by the website's toolbar.
4. Observe the microphone button's behavior.

[Expected result]:
- The microphone button is covered by the website's toolbar.

[Actual results]:
- The microphone button overlaps the website's toolbar content and text.

[Notes]:
- Here is a screencast of the issue:

![whatsapp](https://user-images.githubusercontent.com/26000308/27914058-b8572128-626a-11e7-9f88-2430b26dbd8c.gif)

**Comment by wresuolc** [comment]
this is because the microphone has a high z-index as requested by security.  I'm not sure we can do anything about this.  Also see #13
