### ISSUE TITLE
Voice Fill doesn't display the result of recording and becomes unresponsive

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#46]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b6

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.0 -dev, built on 06/07/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to a search engine website (e.g. www.google.com).
2. Click on the microphone button.
3. Click on "Allow" and say a word.
4. Wait for ~6 seconds and observe what happens next.

[Expected result]:
- The spoken word is displayed as text.

[Actual results]:
- No text is displayed and the add-on becomes unresponsive.

[Notes]:
- The unresponsive dialog box remains blocked in the same place if the page is scrollable.
- The dialog box shrinks if clicked, but remains in the same unresponsive state.
- Here is a screencast of the issue:

![dialog box](https://user-images.githubusercontent.com/26000308/27914397-afcdb476-626b-11e7-892f-271e33b4e2ce.gif)

**Comment by wresuolc** [comment]
This is broken because the old XPI is pointing to the old server.  Andre will send a link to a new XPI
