### ISSUE TITLE
Fail gracefully

### ISSUE THREAD

**Issue by andrenatal** [mozilla/speaktome#47]
In case the server responds status code > 500, or when the response is not a json, and etc.. we should fail gracefully an display an error message.

**Comment by johngruen** [comment]
@andrenatal will write a single handler to deal with all errors by monday morning and I'll add final UI polish then.

**Comment by andrenatal** [comment]
@johngruen [this](https://github.com/mozilla/speaktome/blob/master/extension/content.js#L574) is the spot to add the failure UI animation. 

I'll finish mapping the rest of errors tomorrow morning, but the handle for` fetch` is already there. To reproduce, we need the `fetch` to post the audio to STT fails. 

To do that, you can either turnoff your wifi before start recognizing or replace the [endpoint here](https://github.com/mozilla/speaktome/blob/master/extension/content.js#L17) by a wrong url, like `https://speaktome.services.mozilla.co` for example.
