### ISSUE TITLE
Create basic CLI test

### ISSUE THREAD

**Issue by pdehaan** [mozilla/speaktome#53]
@andrenatal,

How would we test this from the CLI (for load testing)?

I found [this `fetch()`](https://github.com/mozilla/speaktome/blob/7649e86d0949e1f0ad8ffa2639ab2512c64a0afa/extension/content.js#L320-L337) call which seems to POST a blob to the stage server.

Is there an easy we can capture some Blobs from the client side (or somewhere) so we can send them through to the proxy server to get us started w/ the load testing?

Once we have this working from the CLI, it should hopefully be "easy" to convert to a Python script and then run it at scale on AWS to do some load testing on the proxy server to see how many incoming connections/blobs it can process before 🔥.

**Comment by andrenatal** [comment]
Peter, 

it is better and easier if you record and convert to opus locally. Just install sox and opustools `brew install sox opustools` and run the script below. 

This script will run endless until you hit `ctrl+c`  and record what you say for 4 seconds, encode the audio to opus, submit to the api, display the results and store it. 

Each utterance is saved as  `.opus` and the results in a `.txt` file so you can use them in your automated testing interface.
 
```
#!/bin/sh

while [ 1 ]
do
rec _test.wav trim 0 4
sox _test.wav -c 1 -r 16000 -b 16 test$i.wav
opusenc test$i.wav test$i.opus
curl -H "Content-Type: application/octet-stream" --data-binary @test$i.opus https://speaktome.stage.mozaws.net/asr  -o test$i.txt
more test$i.txt
rm _test.wav
rm test$i.wav
i=$[$i+1]
done
```
