### ISSUE TITLE
Ensure that metrics are not sent if DNT is enabled.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/speaktome#54]
You can detect this in a [background page](https://developer.mozilla.org/Add-ons/WebExtensions/manifest.json/background) by inspecting `navigator.doNotTrack`.

**Comment by chuckharmston** [comment]
v0.1.2 of [`testpilot-ga`](https://github.com/mozilla/testpilot-ga) automatically handles this.

**Comment by chuckharmston** [comment]
@andrenatal Are you sure this works? 😜

**Comment by andrenatal** [comment]
@chuckharmston Yes, the reason that was preventing the submit for me a couple of days ago was that DNT was enabled. After I enable it, then started sending.
