### ISSUE TITLE
Make sure correct sites work correctly

### ISSUE THREAD

**Issue by johngruen** [mozilla/speaktome#65]
I think i kinda messed up a few of the required buttons. I'll dive into that code tomorrow!

**Comment by pdehaan** [comment]
@johngruen Do we have a definitive list of supported pages/sites?

I vaguely recalled these from the [manifest.json](https://github.com/mozilla/speaktome/blob/692a8c45a0987f80e41df690c70d6d46dec52d2b/extension/manifest.json#L19-L30), but wasn't sure if there were others (and the README is pretty light):

```
      "matches": [
        "https://www.google.com/*",
        "https://www.google.com/",
        "https://www.google.co.uk/*",
        "https://www.google.co.uk/",
        "https://duckduckgo.com/",
        "https://duckduckgo.com/*",
        "https://yahoo.com/",
        "https://yahoo.com/*",
        "https://uk.yahoo.com/",
        "https://uk.yahoo.com/*"
      ],
```

**Comment by pdehaan** [comment]
Follow on question, what's the expected behavior on non-supported sites? For example, in #31 and #42.
