### ISSUE TITLE
Voice fill overlay is not dismissed if the microphone permission is not granted

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#67]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b10

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.1 -dev built on 07/20/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone button.
3. Click on "Don't Allow" option from the permission door hanger and observe what happens next.

[Expected result]:
- The Voice fill overlay is dismissed. 

[Actual results]:
- The Voice fill overlay is still displayed on website's content area.

[Notes]:
- The overlay is not dismissed even by clicking the "close" button on the top right side of it.
- This issue is also reproducible on https://duckduckgo.com/
- Here is a screen recording with the issue:

![stuck overlay and close button](https://user-images.githubusercontent.com/26000308/28422053-992fa80a-6d6f-11e7-805a-6608c3070e9e.gif)

**Comment by andrenatal** [comment]
This was fixed by: https://github.com/mozilla/speaktome/issues/47 and not reproducible anymore.

**Comment by SoftVision-CarmenFat** [comment]
Confirming that the issue is no longer reproducible on the latest Voice Fill version 1.3.0
An error message is displayed for a few seconds and after that, the overlay is dismissed.
