### ISSUE TITLE
The overlay is wrongly triggered even if the microphone permission is blocked and remembered

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#68]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b10

[Affected Platforms]:
- All Windows
- Al Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.1 -dev built on 07/20/2017) installed.
- Tools -> Page Info -> Permissions -> Use the Microphone -> "Use Default" is unchecked and "Block" is checked.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone button and observe what happens next.

[Expected result]:
- Nothing happens, the overlay is not triggered.
OR
- A notification is displayed stating that there is no permission to access the microphone.

[Actual results]:
- The overlay is triggered and displayed over the website's content area.

[Notes]:
- This issue is also reproducible on https://duckduckgo.com/
- Here is a screen recording with the issue:

![block and remembered](https://user-images.githubusercontent.com/26000308/28422320-53615c6e-6d70-11e7-93f2-a09a38d89904.gif)

**Comment by johngruen** [comment]
Not sure if the right events are exposed...will look into it

**Comment by SoftVision-CarmenFat** [comment]
- This is no longer reproducible on the latest Voice Fill v.1.3.1 (built on 9/29/2017).
- The current behavior is that the overlay is triggered for about 3-4 seconds and it displays the following information: "Please enable your microphone to use Voice Fill".
