### ISSUE TITLE
Clicking one of the multiple answers wrongly starts the search process

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#69]
[Affected versions]:
- Release 54.0.1
- Beta 55.0b10

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.1 -dev built on 07/20/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone button and on "Allow" option from the door hanger permission.
3. Say one word.
4. Click on one of the multiple answers from the drop down and observe what happens.

[Expected result]:
- The clicked answer is displayed in the input having a green background and the following message is displayed at the bottom of the overlay: "Your edits help us train the engine". 

[Actual result]:
- The search starts automatically.

[Additional notes]:
- This is also reproducible on https://duckduckgo.com/
- Added a screen recording with the issue:

![search automatically](https://user-images.githubusercontent.com/26000308/28422534-fe07897c-6d70-11e7-828e-d3af8f30791d.gif)

**Comment by wresuolc** [comment]
This is a google behavior.  The same happens if you just type hello in the search box.
