### ISSUE TITLE
[Nightly] The "Microphone" button is wrongly displayed under the search input

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#79]
[Notes]:
- This is a regression that is present for now only in Nightly and it was introduced by Bugzilla issue 1334550.
- Here is the regression range: 
Last good revision: ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8
First bad revision: 3358bef7a047d347e576bbb83d1461b3776fc5fb
- Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8&tochange=3358bef7a047d347e576bbb83d1461b3776fc5fb

[Affected versions]:
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.2 -dev built on 07/21/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Observe the "Microphone" button and its location on the website.

[Expected result]:
- A white microphone with a turquoise background circle is displayed on the right side of the search input.

[Actual result]:
- There is only a small rectangle button that is displayed on the bottom left of the search input.

[Additional notes]:
- "Warming up..." and "Feedback" text are wrongly displayed on the top left side of the screen.  
- The issue is also reproducible on https://duckduckgo.com/
- Added a screenshot with the issue:

![wrong button](https://user-images.githubusercontent.com/26000308/28465062-2c1bdc9a-6e30-11e7-86f4-61152981b674.png)

**Comment by johngruen** [comment]
@SoftVision-CarmenFat I cannot reproduce this in 56.0a1 (2017-07-23) with the 1.2.3 add-on

**Comment by SoftVision-CarmenFat** [comment]
Tested with latest Nightly build 56.0a1 (2017-07-23) and Voice Fill v.1.2.3 across platforms and I can't reproduce it anymore.
