### ISSUE TITLE
[Nightly] The overlay is not displayed after clicking the "Microphone" button

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#80]
[Notes]:
- This is a regression that is present for now only in Nightly and it was introduced by Bugzilla issue 1334550.
- Here is the regression range: 
Last good revision: ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8
First bad revision: 3358bef7a047d347e576bbb83d1461b3776fc5fb
- Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8&tochange=3358bef7a047d347e576bbb83d1461b3776fc5fb

[Affected versions]:
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.2 -dev built on 07/21/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone/rectangle button and observe what happens next.

[Expected result]:
- The microphone permission prompt is triggered.
- The overlay is displayed on the top of the website area, overlapping its content.

[Actual result]:
- The animation painting a big microphone and "Listening..." text are overlapped by the triggered microphone permission prompt.

[Additional notes]:
- The issue is also reproducible on https://duckduckgo.com/
- Added a screen recording with the issue:

![overlay wrongly displayed](https://user-images.githubusercontent.com/26000308/28465299-e9326eca-6e30-11e7-9d51-0ab773ec14e4.gif)

**Comment by johngruen** [comment]
@SoftVision-CarmenFat I cannot reproduce this in 56.0a1 (2017-07-23) with the 1.2.3 add-on

**Comment by SoftVision-CarmenFat** [comment]
Tested with latest Nightly build 56.0a1 (2017-07-23) and Voice Fill v.1.2.3 across platforms and I can't reproduce it anymore.
