### ISSUE TITLE
[Nightly] The recording animation is wrongly displayed on the left side of the website

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#81]
[Notes]:
- This is a regression that is present for now only in Nightly and it was introduced by Bugzilla issue 1334550.
- Here is the regression range: 
Last good revision: ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8
First bad revision: 3358bef7a047d347e576bbb83d1461b3776fc5fb
- Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8&tochange=3358bef7a047d347e576bbb83d1461b3776fc5fb

[Affected versions]:
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.2 -dev built on 07/21/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to www.google.com
2. Click on the microphone/rectangle button and then on "Allow" option from the permission prompt.
3. Say a word and observe how the recording animation is displayed.

[Expected result]:
- The recording microphone animation and "Listening..." text are displayed in the center of the overlay.
- Dimmed recording waves are displayed over the microphone animation while speaking.

[Actual result]:
- The recording animation is displayed on the left side of the screen and then moves back to the top left side of the website when the recording is done.
- The dimmed recording waves are displayed above the microphone animation.

[Additional notes]:
- The "Feedback" link is also wrongly located on the top center of the website's content.
- The issue is also reproducible on https://duckduckgo.com/
- Added a screen recording with the issue:

![recording animation wrong](https://user-images.githubusercontent.com/26000308/28465634-1bd093b0-6e32-11e7-94ca-89ccd0114d7b.gif)

**Comment by johngruen** [comment]
@SoftVision-CarmenFat I cannot reproduce this in 56.0a1 (2017-07-23) with the 1.2.3 add-on

**Comment by SoftVision-CarmenFat** [comment]
Tested with latest Nightly build 56.0a1 (2017-07-23) and Voice Fill v.1.2.3 across platforms and I can't reproduce it anymore.
