### ISSUE TITLE
[Nightly] Multiple answers are wrongly displayed on the top left side of the website

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/speaktome#82]
[Notes]:
- This is a regression that is present for now only in Nightly and it was introduced by Bugzilla issue 1334550.
- Here is the regression range: 
Last good revision: ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8
First bad revision: 3358bef7a047d347e576bbb83d1461b3776fc5fb
- Pushlog:
https://hg.mozilla.org/integration/autoland/pushloghtml?fromchange=ab348cba6c56cf0dfb4acaccee1bfa262ef3b2d8&tochange=3358bef7a047d347e576bbb83d1461b3776fc5fb

[Affected versions]:
- Nightly 56.0a1

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Prerequisites]:
- Have a Firefox profile with the latest Voice Fill version (1.2.2 -dev built on 07/21/2017) installed.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisites and navigate to https://duckduckgo.com/
2. Click on the microphone/rectangle button and then on "Allow" option from the permission prompt.
3. Say a word.
4. Observe the way the multiple answers are displayed and located on the website.

[Expected result]:
- The multiple answers input and drop down are displayed centered in the overlay.
- "Reset" and "Submit" buttons are displayed on the right side of the multiple answers input.

[Actual result]:
- The multiple answers input and drop down are wrongly displayed on the top left side of the website.
- "Reset" and "Submit" buttons are wrongly displayed as 2 small rectangle and square shapes, just under the suggested answers. 

[Additional notes]:
- The "Feedback" link is also wrongly located on the right side of the multiple answers input.
- The functionality of the multiple answers, the "Feedback" link or "Reset" and "Submit" buttons is not affected. 
- The issue is also reproducible on https://www.google.com/ but in this case, none of the multiple answers, "Reset" and "Submit" buttons and "Feedback" link don't work when clicked.
- Added a screen recording with the issue:

![multiple answers](https://user-images.githubusercontent.com/26000308/28465817-d02f0c4c-6e32-11e7-992b-2aa1c1f2e5ad.gif)

**Comment by johngruen** [comment]
I think this issue is now resolved on 56.0a1 (2017-07-23)

**Comment by SoftVision-CarmenFat** [comment]
Tested with latest Nightly build 56.0a1 (2017-07-23) and Voice Fill v.1.2.3 across platforms and I can't reproduce it anymore.
